import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import './globals.css'

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html>
        {/* <body className={cn(`dark:bg-black bg-white`, poppins.className)}> */}
        <body>
          {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={true}
          >
            <ProModal /> */}
            {children}
            {/* <Toaster />
          </ThemeProvider> */}
        </body>
      </html>
    </ClerkProvider>
  )
}